refactoring: split `theme.lua` into separate groups.
craftzdog/solarized-osaka.nvim pull request #51
Opened 2024-12-17 23:56 UTC by killitar

Hi, thanks for the plugin. I refactored it, but I don't know how to do the switching between dark and light themes. I'll have a look at how to do that. Sorry for open and close previous PR, I split one commit into more smaller commits. 

Fixes https://github.com/craftzdog/solarized-osaka.nvim/issues/48.

2024-12-18 01:27 UTC, Redoxahmii commented
Thank you for the work I was meaning to do this myself once i had some time.
If you mean how the day colors are done it inverts the colors that are already defined by converting them hsluv color space which you can find more info on how in the `hsluv.lua` file.
If you mean how to set it in your editor to see `:colorscheme solarized-osaka-day` should work fine.
I just took a quick glance in your commits and you seem to have removed the part that inverts the colors and highlights in `theme.lua` on line 1026 so that might be your clue to why.

2024-12-18 08:12 UTC, killitar commented
If possible I would like to split the different themes into files, like it is done in [tokyonight](https://github.com/folke/tokyonight.nvim/tree/main/lua/tokyonight/colors). And don't use the colour inversion function inside the `theme.lua` file.

2024-12-18 08:26 UTC, Redoxahmii commented
We'll have to wait for @craftzdog to approve cause this is a huge change and see if that's something he thinks should be considered.
In my opinion this just creates an extra part to maintain while the previous one is functional and defeats the purpose of using `hsl` color space.
This still isn't a strong opinion as I don't use day mode enough to say it has faults for how it works currently.

2024-12-18 09:05 UTC, killitar commented
You're right. I have implemented theme switching using the invert function. If @craftzdog decides to split topics, another PR can be opened in the future.

2024-12-24 13:08 UTC, craftzdog commented
Hi, thanks for the work!
Regarding the day mode, the original Solarized themes have light and dark modes, and this theme is based on the dark one.
If you are interested in adding the day mode, it should rather refer to the light one than just inverting the palette.

Here is the reference: https://ethanschoonover.com/solarized/

I'm happy to review this PR. Could you resolve the conflicts?

2024-12-24 16:10 UTC, killitar commented
Thanks for the opportunity to work on this PR. It was one of my first big PRs. If I did anything wrong please post it. I tried to do my best, but there may be some mistakes, as I'm just learning how to work with Git and open source projects. I would really like to work on another PR after the holidays. I would like to separate the Kinds that are used in `lsp symbol`, `сmp` and `blink.cmp` as it is done in [tokyonight.](https://github.com/folke/tokyonight.nvim/blob/main/lua/tokyonight/groups/kinds.lua). What are your thoughts on this?. Merry Christmas @craftzdog. Thanks for the great plugin

2025-01-06 01:15 UTC, craftzdog requested changes
Found a couple of mismatches between plugin definitions and filenames.

2025-01-06 01:15 UTC, craftzdog commented on lua/solarized-osaka/groups/glyph-pallete.lua
Misspell on the filename

2025-01-06 01:15 UTC, craftzdog commented on lua/solarized-osaka/groups/init.lua
> +  ["rainbow-delimiters.nvim"]       = "rainbow",
`rainbow.lua` does not exit

2025-01-06 08:56 UTC, craftzdog approved these changes
LGTM
Can you please merge this if it looks good to you? @redoxahmii

2025-01-06 14:45 UTC, redoxahmii commented
LGTM

2025-01-06 14:45 UTC, merged